spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/readz
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    baseline-on-migrate: true

jwt:
  key: ${JWT_SECRET}

logging:
  level:
    org:
      springframework:
        security: DEBUG